### ISSUE TITLE
Multiple selection in Safari (No pointer down event after losing focus)

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp#320]
在没有按shift的情况下，mac和ipad在操作rmp时，在进行站点操作时容易误认为是多选，浪费很多时间，望早日修复！谢谢！

Without pressing the Shift key, it is easy to mistakenly consider it as multiple selections when operating RMP on Mac and iPad during site operations, wasting a lot of time. I hope it can be fixed soon! Thank you!

**Comment by thekingofcity** [comment]
Can not reproduce this problem on my iPad. Will this happen every time you touch? If not, under which situation will you encounter this behavior?

cc @wongchito 

https://github.com/railmapgen/rmp/blob/121f4ed9b3691d3a2a30cccdafe5d05a2b1897e0/src/components/svg-canvas-graph.tsx#L57

**Comment by Windows-Taskmgr** [comment]
This is not the case with every touch, but when you modify some settings of one site and then click on another site.

https://github.com/railmapgen/rmp/assets/99594702/b0709529-2d7c-49dc-bd71-1770f3f6c246

**Comment by thekingofcity** [comment]
I still can not reproduce this problem on Windows or iPad OS :(

**Comment by wongchito** [comment]
> This is not the case with every touch, but when you modify some settings of one site and then click on another site.


I'm able to reproduce the issue with the any one of the following setups:
* Safari on Mac using RMP PRD (exact same procedure needed for reproducing the issue)
* Safari on Mac using RMP local (station is selected twice in every clicked)
* Chrome on Mac using RMP local (station is selected twice in every clicked)

<img width="469" alt="image" src="https://github.com/railmapgen/rmp/assets/9390786/0223982c-8e1a-4480-8f32-a9b4f2abb8f0">

**Comment by wongchito** [comment]
I'm not exactly sure about the root cause, but I suspect it relates to the use of `useEvent` and `useDispatch` in https://github.com/railmapgen/rmp/blob/main/src/components/svg-canvas-graph.tsx#L46-L60. 

I would suggest trying to combine the actions `clearSelected` and `addSelected`, and dispatch them in one go, to avoid reference error. 

If this doesn't fix the issue, I would suggest removing `useEvent` completely as we're not sure about the lifecycle of the callback when there're multiple hooks used in it.

**Comment by Windows-Taskmgr** [comment]
So, how can you fix this bug? Thanks!

**Comment by Windows-Taskmgr** [comment]
> 
So, how can you fix this bug? Thanks!

**Comment by Windows-Taskmgr** [comment]
So, how can you fix this bug? Thanks!

**Comment by 28yfang** [comment]
Update: I use Chrome and this problem also appears a lot.

**Comment by langonginc** [comment]
https://github.com/railmapgen/rmp/blob/3ccea1bf4e88d1d976795a0e47676d31c577cde4/src/components/svg-canvas-graph.tsx#L153-L154

L154 may cause this issue.

**Comment by langonginc** [comment]
I reproduced in Edge.

1. Click a node.
2. Click left panel (e.g. Shanghai Metro Basic Station).
3. Pointer down in canvas **and hold for a moment**.
4. You will see multi-selected two nodes.

**Comment by langonginc** [comment]
We set _mode_ to `free` in `handleBackgroundDown()` in `svg-wrapper.tsx` when our pointer is down and add the new node to the canvas.

Then we want to display the details of the new node, so we **add** the _id_ of the new node to _selected_ when the pointer is up and it is still on the new node. **Here, I think the L154 should be `setSelected(node)`.**

---

**Why does it not always happen?**

When we add a node with a quick clicking, it will not happen. But when we click it slowly to add a node, it will happen. That's why it looks like _always_ happening on iPad/MacBook, which we often use without a mouse (Our finger pressing is slower than mouse clicking). 

**But why it is different between clicking fast and slowly?**

> This is my guess. Hope it is right.

Our click can be faster than the application generating new node for you, so there is no new node on the canvas and you won't trigger `handlePointerUp()` in `svg-canvas-graph.tsx`.

**Comment by langonginc** [comment]
Fast clicking:

<img width="722" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/7bc03208-ffcf-4247-8558-27ed313e0208">

---

Slowly clicking:

<img width="721" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/0458256c-e66b-45a6-a8d7-ea70bc7ba616">
