### ISSUE TITLE
Auto simple path when k=0,1,-1,∞

### ISSUE THREAD

**Issue by Lu-Junwen** [railmapgen/rmp#409]
<img width="167" alt="截屏2023-08-16 21 42 17" src="https://github.com/railmapgen/rmp/assets/119102527/bec5e0d7-f02d-4821-b7c9-74249a83877c">
<img width="383" alt="截屏2023-08-16 21 43 21" src="https://github.com/railmapgen/rmp/assets/119102527/1e305ca0-9cfd-48d2-bf39-02d4d4ff6462">
Though I can, in ordinary cases, use lines with 135° or 90° to reach the same effect while things get worse adding an offset to the lines when it is not identical with previous cases, when function "adding straight lines" hasn't been removed.

**Comment by thekingofcity** [comment]
Hi, thanks for the suggestion. We have tweaked the app so that in some cases, the simple path will be automatically used. This should help fix the problem shown.

1. offsetFrom and offsetTo are defined, numbers and equal AND
2. The combination of slope (k) and type is one of the following cases:
  2.1. k = 0 or ∞ and type is Diagonal or Perpendicular OR
  2.2. k = 1 or -1 and type is Diagonal or RotatePerpendicular

![image](https://github.com/railmapgen/rmp/assets/3353040/9e22d496-c281-411e-95f5-9ad62226513f)

> Note that the path has no curve on both ends.
