### ISSUE TITLE
Name offsets reset after changing station styles in batch

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#518]
As written in the title, the name offsets reset after pressing the button :)

**Comment by thekingofcity** [comment]
Okay, so as the modal suggests, all attributes except the names and positions will be reset after changing station styles in batch.

![image](https://github.com/railmapgen/rmp/assets/3353040/4e3b5ba1-6b5c-4e95-ba8b-ec3801c6b511)

This is by design as some stations do not use name offsets as their way to display station names :)
