### ISSUE TITLE
Issue with parallel lines notification

### ISSUE THREAD

**Issue by CarolStott** [railmapgen/rmp#841]
Hi,

I have found that I keep on getting this notification:
_Parallel lines exceed the free tier. Remove them to dismiss this warning, or subscribe to unlock more!_
I am subscribed to the tier that allows unlimited parallel lines, and I am always logged in to my account. My subscription is also still valid, and doesn't expire until August next year.

Regards,
Carol

**Comment by thekingofcity** [comment]
Hi, sorry for the inconvenience. Would you like to check your subscription status in the settings? It should be something like this.

![image](https://github.com/user-attachments/assets/d9a5c152-d039-4d21-bcd0-6e53cbd61dd4)

If not, make sure you are logged in to the left side panel. If the status is still not the correct one, you may click on the right-side button to refresh your subscription status.

Bests,
thekingofcity

**Comment by CarolStott** [comment]
Hi,

It looks like that and I am logged in, and yet I still get that notification.

Regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

Would you like to take the following screenshot? Make sure the right-side refresh button is clicked before taking it.

![image](https://github.com/user-attachments/assets/ac900aff-9ed3-4979-944d-b78f405ce0a7)

Bests,
thekingofcity

**Comment by CarolStott** [comment]
![image](https://github.com/user-attachments/assets/0d1cd5ac-4bc9-45a6-b50b-5444d239f8c4)

**Comment by thekingofcity** [comment]
After closing the warning, would it appear again after any actions such as moving/adding stations and lines?

**Comment by thekingofcity** [comment]
And are you able to put more master nodes (>3) under this scenario?

**Comment by CarolStott** [comment]
Yes, I can, just the parallel lines don't work

**Comment by thekingofcity** [comment]
I see that _Automatically set new lines to be parallel to existing lines_ is set to true, so there should be no issues when you create new lines or edit the parallel index of existing lines.

If the warning won't appear again after you close it, I would suspect that the warning shows because of the wrong subscription state on the initial load. Let me know if that's the case.

**Comment by CarolStott** [comment]
Thanks, I'll try that tomorrow morning. If it's the latter, I wouldn't be too surprised as the subscription page was all in Chinese, so there was bound to be something lost in translation.

**Comment by thekingofcity** [comment]
In fact, I would say the page doesn't mention anything in detail except that you can unlock several pro features with the subscription. It's been less than a month since this subscription is online so there might be some bugs :( Rest assured, there will be compensation if this is a bug :)

I'd be happy if there is some similar worldwide English platform that can automatically reply with some preset messages upon payment. Opencollective obviously not and I'm not sure if others can.

**Comment by CarolStott** [comment]
I assumed it had been up for longer - if it's only been up for a month then that's totally understandable, take your time.

I'm sure there are plenty of English language services like the one you're using, but considering where you are (Shanghai, I believe?) I imagine it might be a bit awkward.

**Comment by thekingofcity** [comment]
Yeah, the payment could be tricky but I'll check them out to see if any services meet both automatic preset messages reply and payment. Just naming a few would be helpful for a start :)

**Comment by thekingofcity** [comment]
> If the warning won't appear again after you close it, I would suspect that the warning shows because of the wrong subscription state on the initial load. Let me know if that's the case.

I confirmed that this could be a case of the warning showing on the first load. But there could be other reasons for the problem. If this is the root cause for the problem, I'll fix it but not with the top priority as the workaround only needs one click :)

**Comment by thekingofcity** [comment]
#847 is fixed. Let me know if you are still encountering this problem.

Feel free to comment to close this issue :)
