### ISSUE TITLE
Fix name offset of London Underground basic station

### ISSUE THREAD

**Issue by CarolStott** [railmapgen/rmp#853]
Hi,

Sorry to bother you again, but I have noticed that there are discrepancies in the distances between the label and the mark for a TfL station. I have attached a screenshot of what I have gotten in RMP, and the official diagram standards for the stations which might help.

In case it isn't clear, 'x' or 'n' is the line width. For example, the distance between the text and the line should be 1.33 × the line width if the line is horizontal, or 3 × the line width if the line is vertical. From what I gather, this is regardless of unit - you may need a calculator though!

One problem with the document TfL provides is that it doesn't provide any guidance for diagonal stations, even though there are diagonal stations on the official maps. The document is from 2009, but I can't seem to find a more recent edition.

Regards,
Carol

![Untitled](https://github.com/user-attachments/assets/35c228da-e301-474b-98ad-413ed4198834)
![Untitled 2](https://github.com/user-attachments/assets/33400427-e6d6-4561-b434-91d7afc78b25)
![Untitled 3](https://github.com/user-attachments/assets/174f4ed5-8b13-46a3-bc83-ea9b4f408c71)
![Untitled 4](https://github.com/user-attachments/assets/b14499c2-f895-4056-a7e5-e337da4d0cf4)

**Comment by thekingofcity** [comment]
Hi, thanks for pointing out. There is a fix in the [UAT](https://uat-railmapgen.github.io/?app=rmp) version `5.1.0.#853-Fix-name-offset-of-London-Underground-basic-station.50a9c44` and let me know if it is expected there.

![image](https://github.com/user-attachments/assets/f6347007-ec9c-4bb5-8d01-bd10d976932a)

PS: For #841, kindly reply whether the issue if fix otherwise I'll consider it as solved :)

**Comment by thekingofcity** [comment]
Fixed in 5.1.1
